from typing import Optional, List
from fastapi import APIRouter, Depends, Request, HTTPException
from pydantic import BaseModel
from google.cloud.firestore_v1 import Client as FirestoreClient

from app.db.database import get_db
from app.api.deps import get_current_user
from app.core.rate_limit import limiter


router = APIRouter()


class SyncOperation(BaseModel):
    collection: str
    document_id: str
    data: dict
    operation: str  # "set", "update", "delete"
    timestamp: str


class SyncUploadRequest(BaseModel):
    device_id: str
    operations: List[SyncOperation]


class SyncDownloadRequest(BaseModel):
    device_id: str
    last_sync_version: Optional[str] = None


@router.post("/upload")
@limiter.limit("30/minute")
def sync_upload(
    request: Request,
    payload: SyncUploadRequest,
    db: FirestoreClient = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """
    Receives local operations from a device and applies them to Firestore.
    Also detects habit streak milestones and sends a celebration email.
    """
    uid = current_user["uid"]
    
    if len(payload.operations) > 500:
        raise HTTPException(status_code=400, detail="Too many operations in a single sync request (max 500).")

    applied = 0

    for op in payload.operations:
        ref = db.collection("users").document(uid).collection(op.collection).document(op.document_id)
        try:
            if op.operation == "delete":
                ref.delete()
            elif op.operation == "set":
                ref.set(op.data)
            elif op.operation == "update":
                ref.set(op.data, merge=True)
            applied += 1

        except Exception as e:
            print(f"Failed to apply op {op.document_id}: {e}")

    return {"applied": applied, "total": len(payload.operations)}


@router.post("/download")
@limiter.limit("30/minute")
def sync_download(
    request: Request,
    payload: SyncDownloadRequest,
    db: FirestoreClient = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """
    Returns all user data converted into an operations list so the Flutter client can re-hydrate offline storage.
    """
    uid = current_user["uid"]
    # The actual collection names generated by Flutter's SyncService 'entityType' field
    collections = [
        "flashcard", "flashcard_deck", "daily_reflection", 
        "event", "water_log", "workout"
    ]

    import time
    new_version = int(time.time() * 1000)
    
    operations = []
    
    for col in collections:
        docs = db.collection("users").document(uid).collection(col).stream()
        for doc in docs:
            doc_data = doc.to_dict()
            operations.append({
                "entity_type": col,
                "entity_id": doc.id,
                "operation_type": "update",
                "payload": doc_data
            })

    return {
        "new_last_sync_version": new_version,
        "operations": operations
    }
