"""Add Flashcards and LiveFocusSessions

Revision ID: 4c1540049652
Revises: af01c22ff8e0
Create Date: 2026-08-05 22:01:50.236806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c1540049652'
down_revision: Union[str, Sequence[str], None] = 'af01c22ff8e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reflections',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('highlights', sa.Text(), nullable=True),
    sa.Column('improvements', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_reflections_user_id'), 'daily_reflections', ['user_id'], unique=False)
    op.create_index(op.f('ix_daily_reflections_version'), 'daily_reflections', ['version'], unique=False)
    op.create_table('flashcard_decks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcard_decks_user_id'), 'flashcard_decks', ['user_id'], unique=False)
    op.create_index(op.f('ix_flashcard_decks_version'), 'flashcard_decks', ['version'], unique=False)
    op.create_table('live_focus_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_activity', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_ping_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_focus_sessions_user_id'), 'live_focus_sessions', ['user_id'], unique=True)
    op.create_index(op.f('ix_live_focus_sessions_version'), 'live_focus_sessions', ['version'], unique=False)
    op.create_table('study_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('content_link', sa.String(), nullable=True),
    sa.Column('ambient_sound', sa.String(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_sessions_user_id'), 'study_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_study_sessions_version'), 'study_sessions', ['version'], unique=False)
    op.create_table('flashcards',
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('front_content', sa.Text(), nullable=False),
    sa.Column('back_content', sa.Text(), nullable=False),
    sa.Column('ease_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['flashcard_decks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcards_deck_id'), 'flashcards', ['deck_id'], unique=False)
    op.create_index(op.f('ix_flashcards_version'), 'flashcards', ['version'], unique=False)
    op.drop_table('waitlist')
    op.add_column('habit_logs', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('habits', sa.Column('icon_code', sa.String(), nullable=True))
    op.add_column('habits', sa.Column('category', sa.String(), nullable=True))
    op.add_column('habits', sa.Column('frequency_type', sa.String(), server_default='daily', nullable=False))
    op.add_column('habits', sa.Column('target_weekdays', sa.JSON(), nullable=True))
    op.add_column('habits', sa.Column('target_times_per_week', sa.Integer(), nullable=True))
    op.add_column('habits', sa.Column('reminder_time', sa.DateTime(), nullable=True))
    op.add_column('habits', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.add_column('habits', sa.Column('is_paused', sa.Boolean(), nullable=True))
    op.add_column('habits', sa.Column('available_freezes', sa.Integer(), nullable=True))
    op.add_column('habits', sa.Column('season_id', sa.String(), nullable=True))
    op.add_column('habits', sa.Column('freezes_used_log', sa.JSON(), nullable=True))
    op.add_column('habits', sa.Column('pause_windows', sa.JSON(), nullable=True))
    op.add_column('habits', sa.Column('best_streak', sa.Integer(), nullable=True))
    op.alter_column('habits', 'frequency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('otp_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('otp_attempts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_attempts')
    op.drop_column('users', 'otp_expires_at')
    op.drop_column('users', 'otp_hash')
    op.drop_column('users', 'is_verified')
    op.alter_column('habits', 'frequency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('habits', 'best_streak')
    op.drop_column('habits', 'pause_windows')
    op.drop_column('habits', 'freezes_used_log')
    op.drop_column('habits', 'season_id')
    op.drop_column('habits', 'available_freezes')
    op.drop_column('habits', 'is_paused')
    op.drop_column('habits', 'is_archived')
    op.drop_column('habits', 'reminder_time')
    op.drop_column('habits', 'target_times_per_week')
    op.drop_column('habits', 'target_weekdays')
    op.drop_column('habits', 'frequency_type')
    op.drop_column('habits', 'category')
    op.drop_column('habits', 'icon_code')
    op.drop_column('habit_logs', 'note')
    op.create_table('waitlist',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='waitlist_pkey'),
    sa.UniqueConstraint('email', name='waitlist_email_key')
    )
    op.drop_index(op.f('ix_flashcards_version'), table_name='flashcards')
    op.drop_index(op.f('ix_flashcards_deck_id'), table_name='flashcards')
    op.drop_table('flashcards')
    op.drop_index(op.f('ix_study_sessions_version'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_user_id'), table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_index(op.f('ix_live_focus_sessions_version'), table_name='live_focus_sessions')
    op.drop_index(op.f('ix_live_focus_sessions_user_id'), table_name='live_focus_sessions')
    op.drop_table('live_focus_sessions')
    op.drop_index(op.f('ix_flashcard_decks_version'), table_name='flashcard_decks')
    op.drop_index(op.f('ix_flashcard_decks_user_id'), table_name='flashcard_decks')
    op.drop_table('flashcard_decks')
    op.drop_index(op.f('ix_daily_reflections_version'), table_name='daily_reflections')
    op.drop_index(op.f('ix_daily_reflections_user_id'), table_name='daily_reflections')
    op.drop_table('daily_reflections')
    # ### end Alembic commands ###
