"""Add AI quota fields

Revision ID: 5b1c82002bab
Revises: 9a7648196fe9
Create Date: 2026-07-23 15:01:38.416450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b1c82002bab'
down_revision: Union[str, Sequence[str], None] = '9a7648196fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('last_sync_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('devices', sa.Column('push_token', sa.String(), nullable=True))
    op.add_column('habits', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'habits', 'categories', ['category_id'], ['id'])
    op.alter_column('sync_operations', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.add_column('user_settings', sa.Column('ai_features_enabled', sa.Boolean(), nullable=True))
    op.add_column('user_settings', sa.Column('ai_requests_used', sa.Integer(), nullable=False))
    op.add_column('user_settings', sa.Column('ai_quota_reset_at', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'ai_quota_reset_at')
    op.drop_column('user_settings', 'ai_requests_used')
    op.drop_column('user_settings', 'ai_features_enabled')
    op.alter_column('sync_operations', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'habits', type_='foreignkey')
    op.drop_column('habits', 'category_id')
    op.drop_column('devices', 'push_token')
    op.drop_column('devices', 'last_sync_time')
    # ### end Alembic commands ###
