"""Add new entities and version columns

Revision ID: 9a7648196fe9
Revises: 60f25c498e88
Create Date: 2026-07-23 07:47:59.379078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a7648196fe9'
down_revision: Union[str, Sequence[str], None] = '60f25c498e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('daily_water_goal_ml', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_settings_version'), 'user_settings', ['version'], unique=False)
    op.create_table('water_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount_ml', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_logs_user_id'), 'water_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_water_logs_version'), 'water_logs', ['version'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_workout_sessions_version'), 'workout_sessions', ['version'], unique=False)
    op.create_table('transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_transactions_version'), 'transactions', ['version'], unique=False)
    op.create_table('workout_sets',
    sa.Column('workout_session_id', sa.UUID(), nullable=False),
    sa.Column('exercise_name', sa.String(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sets_version'), 'workout_sets', ['version'], unique=False)
    op.create_index(op.f('ix_workout_sets_workout_session_id'), 'workout_sets', ['workout_session_id'], unique=False)
    op.add_column('calendar_events', sa.Column('version', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_calendar_events_version'), 'calendar_events', ['version'], unique=False)
    op.add_column('categories', sa.Column('category_type', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('version', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_categories_version'), 'categories', ['version'], unique=False)
    op.add_column('goal_progress', sa.Column('version', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_goal_progress_version'), 'goal_progress', ['version'], unique=False)
    op.add_column('goals', sa.Column('version', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_goals_version'), 'goals', ['version'], unique=False)
    op.add_column('habit_logs', sa.Column('version', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_habit_logs_version'), 'habit_logs', ['version'], unique=False)
    op.add_column('habits', sa.Column('version', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_habits_version'), 'habits', ['version'], unique=False)
    op.add_column('journals', sa.Column('version', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_journals_version'), 'journals', ['version'], unique=False)
    op.add_column('notes', sa.Column('version', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_notes_version'), 'notes', ['version'], unique=False)
    op.add_column('reminders', sa.Column('version', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_reminders_version'), 'reminders', ['version'], unique=False)
    op.add_column('tasks', sa.Column('version', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_tasks_version'), 'tasks', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_version'), table_name='tasks')
    op.drop_column('tasks', 'version')
    op.drop_index(op.f('ix_reminders_version'), table_name='reminders')
    op.drop_column('reminders', 'version')
    op.drop_index(op.f('ix_notes_version'), table_name='notes')
    op.drop_column('notes', 'version')
    op.drop_index(op.f('ix_journals_version'), table_name='journals')
    op.drop_column('journals', 'version')
    op.drop_index(op.f('ix_habits_version'), table_name='habits')
    op.drop_column('habits', 'version')
    op.drop_index(op.f('ix_habit_logs_version'), table_name='habit_logs')
    op.drop_column('habit_logs', 'version')
    op.drop_index(op.f('ix_goals_version'), table_name='goals')
    op.drop_column('goals', 'version')
    op.drop_index(op.f('ix_goal_progress_version'), table_name='goal_progress')
    op.drop_column('goal_progress', 'version')
    op.drop_index(op.f('ix_categories_version'), table_name='categories')
    op.drop_column('categories', 'version')
    op.drop_column('categories', 'category_type')
    op.drop_index(op.f('ix_calendar_events_version'), table_name='calendar_events')
    op.drop_column('calendar_events', 'version')
    op.drop_index(op.f('ix_workout_sets_workout_session_id'), table_name='workout_sets')
    op.drop_index(op.f('ix_workout_sets_version'), table_name='workout_sets')
    op.drop_table('workout_sets')
    op.drop_index(op.f('ix_transactions_version'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_workout_sessions_version'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_user_id'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index(op.f('ix_water_logs_version'), table_name='water_logs')
    op.drop_index(op.f('ix_water_logs_user_id'), table_name='water_logs')
    op.drop_table('water_logs')
    op.drop_index(op.f('ix_user_settings_version'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
